const sceneStyles=document.createElement('link');sceneStyles.rel='stylesheet';sceneStyles.href='scene.css';document.head.append(sceneStyles);const $=s=>document.querySelector(s);let questions=[],player={},roomCode='',roundId='',index=0,locked=false,startedAt=0,players=[],finalLeaders=[];const sdk=window.ClassroomGameSDK.create({parentOrigin:location.origin});
sdk.onMessage(message=>{if(message.type==='loadContent'){questions=message.payload.questions||[];index=Math.min((player.correct||0)+(player.incorrect||0),Math.max(questions.length-1,0))}if(message.type==='startGame')render();if(message.type==='endGame')summary(finalLeaders)});const announceReady=()=>sdk.send({type:'gameReady',payload:{gameId:'pea-tightrope-mcq',version:'1.0.0'}});announceReady();setTimeout(announceReady,500);
addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==parent||!e.data?.type)return;if(e.data.type==='gameContext'){({player,roomCode,roundId,players}=e.data.payload);index=Math.min((player.correct||0)+(player.incorrect||0),Math.max(questions.length-1,0))}if(e.data.type==='rosterUpdate')players=e.data.payload.players||players;if(e.data.type==='answerResult')result(e.data.payload);if(e.data.type==='gameSummary')finalLeaders=e.data.payload.leaderboard||[]});
function render(){if(!questions.length)return;locked=false;startedAt=performance.now();const q=questions[index];$('#progress').textContent=`Câu ${index+1}/${questions.length}`;$('#score').textContent=`${player.score||0} điểm`;$('#prompt').textContent=q.prompt;$('#options').innerHTML='';q.options.forEach((o,i)=>{const b=document.createElement('button');b.className='option';b.textContent=`${String.fromCharCode(65+i)}. ${o.text}`;b.onclick=()=>submit(o.id);$('#options').append(b)});setProgress();}
function submit(answer){if(locked)return;locked=true;document.querySelectorAll('.option').forEach(b=>b.disabled=true);parent.postMessage({type:'answerAttempt',payload:{playerId:player.playerId,questionId:questions[index].id,answer,roundId,timeMs:Math.round(performance.now()-startedAt)}},location.origin)}
function result(r){if(r.questionId!==questions[index]?.id)return;player.score=r.score;player.correct=(player.correct||0)+(r.isCorrect?1:0);player.incorrect=(player.incorrect||0)+(r.isCorrect?0:1);$('#score').textContent=`${player.score} điểm`;const pea=$('#pea'),fb=$('#feedback');pea.classList.remove('walk','fall');if(!r.isCorrect){const pr=pea.getBoundingClientRect(),mr=document.querySelector('.safety-mat').getBoundingClientRect();pea.style.setProperty('--fall-x',`${mr.left+mr.width/2-pr.left-pr.width/2}px`);pea.style.setProperty('--fall-y',`${mr.top-pr.bottom+55}px`)}void pea.offsetWidth;pea.classList.add(r.isCorrect?'walk':'fall');$('#pea-img').src=r.isCorrect?'assets/pea-happy.png':'assets/pea-fall.png';fb.textContent=r.isCorrect?'Chính xác! Pea đi bóng thật khéo!':'Hu hu! Pea ngã và khóc rồi, nhưng sẽ thử tiếp nhé! 😭';fb.className=`feedback show ${r.isCorrect?'good':'bad'}`;sdk.send({type:'submitAnswer',payload:{playerId:player.playerId,questionId:r.questionId,answer:r.answer,isCorrect:r.isCorrect,timeMs:Math.round(performance.now()-startedAt)}});sdk.send({type:'updateScore',payload:{playerId:player.playerId,score:r.score,delta:r.delta}});setTimeout(()=>{fb.className='feedback';if(index+1<questions.length){index++;$('#pea-img').src='assets/pea-ready.png';render()}else finish()},1450)}
function setProgress(){const pct=questions.length?index/questions.length*82:0;$('#pea').style.setProperty('--x',`${6+pct}%`)}
function finish(){$('#pea').style.setProperty('--x','88%');$('#pea-img').src='assets/pea-happy.png';$('#prompt').textContent='Pea đã qua dây an toàn!';$('#options').innerHTML='<p class="done">Em đã hoàn thành. Hãy chờ các bạn nhé!</p>'}
function summary(list){const sorted=[...list].sort((a,b)=>b.score-a.score||a.playerId.localeCompare(b.playerId));let last=null,rank=0;const ranked=sorted.map((p,i)=>{if(p.score!==last){rank=i+1;last=p.score}return{playerId:p.playerId,name:p.name,score:p.score,rank:p.rank||rank}});$('#prompt').textContent='Kết quả rạp xiếc';$('#options').innerHTML=`<ol class="podium">${ranked.map(p=>`<li><strong>#${p.rank} ${escapeHtml(p.name)}</strong><span>${p.score} điểm</span></li>`).join('')}</ol>`;$('#pea-img').src='assets/pea-happy.png';sdk.send({type:'gameEnd',payload:{roomCode,leaderboard:ranked}})}
$('#leaderboard-toggle').onclick=()=>{$('#leaderboard').hidden=false;$('#leaders').innerHTML=players.sort((a,b)=>b.score-a.score).map(p=>`<li>${escapeHtml(p.name)} <strong>${p.score}</strong></li>`).join('')};$('#leaderboard-close').onclick=()=>$('#leaderboard').hidden=true;function escapeHtml(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML}
