import{loadQuestionBank,learnerQuestions}from'./content-loader.js';import{createTransport}from'./transport.js';import{freshRoom,loadRoom,saveRoom,publicSnapshot,grade,rankPlayers}from'./room-controller.js';import{bindMute,sound}from'./audio.js';
bindMute();const $=s=>document.querySelector(s);const teacherId=sessionStorage.peaTeacherId||=crypto.randomUUID();let room,bank,transport,renderTimer;
async function init(){try{bank=await loadQuestionBank({url:'content.json'});$('#content-status').textContent=`Đã tải ${bank.questions.length} câu · phiên bản ${bank.contentVersion} · ${new Date(bank.fetchedAt).toLocaleTimeString('vi-VN')}`;$('#bank-name').textContent=bank.name;preview();restoreOrCreate()}catch(e){$('#content-status').textContent=`Lỗi: ${e.message}`}}
function restoreOrCreate(){const oldCode=sessionStorage.peaTeacherRoom,old=oldCode&&loadRoom(oldCode);room=old?.teacherId===teacherId?old:freshRoom(makeCode(),bank,teacherId);sessionStorage.peaTeacherRoom=room.roomCode;saveRoom(room);transport=createTransport().join(room.roomCode);transport.onEvent(onEvent);$('#room-code').textContent=room.roomCode;render();showTeacherSummary();broadcast()}
function makeCode(){let c;do{c='PEA'+Math.floor(100+Math.random()*900)}while(loadRoom(c));return c}
function onEvent(e){if(e.recipientId&&e.recipientId!==teacherId)return;if(e.type==='joinRequest'){let p=room.players.find(x=>x.playerId===e.payload.player.playerId);if(!p&&room.players.length<4){room.players.push(e.payload.player);saveRoom(room)}sendSnapshot(e.payload.player.playerId);render()}if(e.type==='resumeRequest')sendSnapshot(e.senderId);if(e.type==='answerAttempt'){const result=grade(room,e.senderId,e.payload.questionId,e.payload.answer);if(result){transport.send({type:'answerResult',roundId:room.roundId,senderId:teacherId,recipientId:e.senderId,payload:{...result,score:room.players.find(p=>p.playerId===e.senderId).score}});sound(result.isCorrect?'right':'wrong');broadcast();render()}}}
function sendSnapshot(id){transport.send({type:'snapshot',roundId:room.roundId,senderId:teacherId,recipientId:id,payload:{snapshot:publicSnapshot(room,id),questions:room.phase==='playing'?learnerQuestions(room.questions):[]}})}
function broadcast(includeQuestions=false){transport.send({type:'snapshot',roundId:room.roundId,senderId:teacherId,payload:{snapshot:publicSnapshot(room),questions:includeQuestions?learnerQuestions(room.questions):[]}})}
function render(){clearTimeout(renderTimer);renderTimer=setTimeout(()=>{const ranked=rankPlayers(room.players);$('#player-count').textContent=ranked.length;$('#start-btn').disabled=!ranked.length||room.phase==='playing';$('#end-btn').disabled=room.phase!=='playing';$('#replay-btn').hidden=room.phase!=='ended';$('#download-csv').disabled=room.phase!=='ended';$('#room-status').textContent=room.phase==='lobby'?'Chờ học sinh vào phòng':room.phase==='playing'?'Vòng chơi đang diễn ra':'Vòng chơi đã kết thúc';$('#roster').innerHTML=ranked.length?ranked.sort((a,b)=>a.name.localeCompare(b.name,'vi')).map(p=>`<tr><td>${esc(p.name)}</td><td>${p.score}</td><td>${Object.keys(p.answers||{}).length}/${room.questions.length}</td><td>${p.correct}</td><td>${p.incorrect}</td><td>${label(p.status)}</td></tr>`).join(''):'<tr><td colspan="6" class="empty">Chưa có học sinh vào phòng</td></tr>';$('#question-stats').innerHTML=room.questions.map(q=>{const answers=room.players.map(p=>p.answers?.[q.id]).filter(Boolean),ok=answers.filter(a=>a.isCorrect).length;return`<article><strong>${esc(q.prompt)}</strong><span>${answers.length?Math.round(ok/answers.length*100):0}% đúng · ${room.players.length-answers.length} chưa nộp</span></article>`}).join('')},120)}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const label=s=>({waiting:'Đang chờ',playing:'Đang chơi',finished:'Đã xong'}[s]||s);
function preview(){$('#preview').innerHTML=bank.questions.slice(0,3).map((q,i)=>`<p><strong>${i+1}.</strong> ${esc(q.prompt)} <span class="answer-key">Đáp án: ${esc(q.correctOptionId.toUpperCase())}</span></p>`).join('')}
function showTeacherSummary(){let section=$('#teacher-summary');if(!section){section=document.createElement('section');section.id='teacher-summary';section.className='panel';document.querySelector('.teacher-layout').append(section)}section.hidden=room.phase!=='ended';if(section.hidden)return;const ranked=rankPlayers(room.players);section.innerHTML=`<div class="section-head"><div><span class="eyebrow">KẾT QUẢ VÒNG CHƠI</span><h2>🏆 Bảng xếp hạng</h2></div><strong>${ranked.length} học sinh</strong></div><ol class="podium">${ranked.map(p=>`<li><strong><span aria-hidden="true">${p.rank===1?'🥇':p.rank===2?'🥈':p.rank===3?'🥉':'🎪'}</span> Hạng ${p.rank}: ${esc(p.name)}</strong><span>${p.score} điểm · ${p.correct} đúng · ${p.incorrect} sai</span></li>`).join('')}</ol>`}
$('#start-btn').onclick=()=>{room.phase='playing';room.players.forEach(p=>p.status='playing');saveRoom(room);broadcast(true);render();showTeacherSummary()};$('#end-btn').onclick=()=>{room.phase='ended';room.players.forEach(p=>p.status='finished');saveRoom(room);transport.send({type:'endGame',roundId:room.roundId,senderId:teacherId,payload:{leaderboard:rankPlayers(room.players)}});broadcast();render();showTeacherSummary()};$('#replay-btn').onclick=()=>{room.roundId=crypto.randomUUID();room.phase='lobby';room.questions=bank.questions;room.contentVersion=bank.contentVersion;room.fetchedAt=bank.fetchedAt;room.bankName=bank.name;room.players.forEach(p=>Object.assign(p,{score:0,correct:0,incorrect:0,answers:{},status:'waiting'}));saveRoom(room);broadcast();render();showTeacherSummary()};$('#reload-content').onclick=async()=>{try{const next=await loadQuestionBank({url:'content.json'});bank=next;$('#content-status').textContent=`Đã tải ${next.questions.length} câu · phiên bản ${next.contentVersion} · ${new Date(next.fetchedAt).toLocaleTimeString('vi-VN')}`;preview()}catch(e){$('#content-status').textContent=`Không thể cập nhật: ${e.message}. Bản đang dùng vẫn được giữ.`}};
$('#download-csv').onclick=()=>{const ranked=rankPlayers(room.players),heads=['playerId','name','score','correct','incorrect','unanswered','rank'];const safe=v=>{let s=String(v??'');if(/^[=+\-@]/.test(s))s="'"+s;return`"${s.replaceAll('"','""')}"`};const rows=ranked.map(p=>[p.playerId,p.name,p.score,p.correct,p.incorrect,room.questions.length-p.correct-p.incorrect,p.rank]);const blob=new Blob([[heads,...rows].map(r=>(Array.isArray(r)?r:[r]).map(safe).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`pea-${room.roomCode}.csv`;a.click();URL.revokeObjectURL(a.href)};init();
